feature/kafka_service
T1rax/movies_ugc_service pull request #14
Opened 2023-05-09 12:46 UTC by wiky-avis

2023-05-09 16:21 UTC, T1rax requested changes
Мне кажется, четко получилось. Я оставил небольшие коментарии, но ничего критичного не увидел

2023-05-09 16:21 UTC, T1rax commented on src/brokers/kafka_consumer.py
Может тут убрать в названиях файлов кафку? По идее в классах должно быть достаточно.
Тут не критично

2023-05-09 16:21 UTC, T1rax commented on src/brokers/kafka_producer.py
> +    async def setup(cls):
А почему бы это не положить в __init__?

2023-05-09 16:21 UTC, T1rax commented on src/services/user_activity_service.py
> +    producer: KafkaProducer = Depends(KafkaProducer),
По идее в начале должен быть абстрактный класс  - BaseProducer

2023-05-09 16:21 UTC, T1rax commented on src/services/user_activity_service.py
> +    producer: KafkaProducer = Depends(KafkaProducer),
И тут же можно инициализировать producer с чем-то типа get_producer

Получится по итогу что-то такое
`producer: BaseProducer = Depends(get_producer),`

2023-05-09 16:21 UTC, T1rax commented on src/settings/kafka.py
> +load_dotenv()
А зачем он здесь? По идее и без этого должно корректно укзаывать. Dockrer-compose знает где лежит .env файл и его подпушивает

2023-05-09 16:21 UTC, T1rax commented on src/settings/logger.py
> +        "uvicorn.access": {
Может сразу на gunicorn заменить?

Не вижу пока смысла сидеть временно на uvicorn

2023-05-09 16:21 UTC, T1rax commented on src/settings/app.py
Такое ощущение, что уже появилось много переменных в .env файле. Можешь пожалуйста обновить и .env.example?

2023-05-09 16:29 UTC, wiky-avis commented on src/brokers/kafka_consumer.py
а если будут другие косьюмеры?

2023-05-09 16:33 UTC, wiky-avis commented on src/settings/kafka.py
> +load_dotenv()
в предыдущих проектах были случаи что не видел енвы. Думаю лучше оставить, не мешает)

2023-05-09 16:53 UTC, T1rax commented on src/brokers/kafka_consumer.py
Хмммм, в таком случае было бы ок. Но я не вижу при каких условиях появится потребность добавить еще одного брокера сообщений. Просто накидываешь доп топики в кафку

2023-05-09 16:53 UTC, T1rax commented on src/brokers/kafka_producer.py
> +    async def setup(cls):
Логично

2023-05-09 16:56 UTC, T1rax commented on src/services/user_activity_service.py
> +    producer: KafkaProducer = Depends(KafkaProducer),
Еще выше будет зависимость от абстракции, а не от реализации. 

Тебе придется изменить кафку на того же кролика только в get_producer и все. А сейчас хоть и немного, но придется по коду полгулять

2023-05-09 16:56 UTC, T1rax commented on src/settings/kafka.py
> +load_dotenv()
Мне не мешает, но помню на одном из ревью прикопались

2023-05-09 17:10 UTC, wiky-avis commented on src/settings/kafka.py
> +load_dotenv()
хм. нам не делали замечания пока по этому поводу. давай пока оставим)

2023-05-10 14:25 UTC, T1rax approved these changes
Супер

2023-05-10 14:27 UTC, merged