Реализована ёлка (ELK) приложения
T1rax/movies_ugc_service pull request #57
Opened 2023-05-26 16:58 UTC by opodryadov

2023-05-27 06:37 UTC, wiky-avis commented on docker-compose-base.yml
> +  nginx:
зачем это в этом файле? все что связано с елкой тоже не нужно по-моему в базовом файле.

2023-05-27 06:37 UTC, wiky-avis commented on docker-compose-local.yml
> +  nginx:
тот же вопрос? на фига это поднимать каждый раз локально? логи у тебя и так в терминале будут отображаться. Файл локал нужен для локального запуска и тестирования, Елку вряд ли нужно постоянно тестировать. По-моему лучше все что связано с елкой перенести в продовый файл, чтобы не понимать это каждый раз

2023-05-27 06:37 UTC, wiky-avis commented on pyproject.toml
> +sentry-sdk = {extras = ["fastapi"], version = "^1.24.0"}
версии лучше фиксировать

2023-05-29 16:57 UTC, opodryadov commented on docker-compose-base.yml
> +  nginx:
Вынес в отдельный каталог все что связано с ELK

2023-05-29 16:58 UTC, opodryadov commented on docker-compose-local.yml
> +  nginx:
Вынес в отдельный каталог все что связано с ELK

2023-05-29 16:58 UTC, opodryadov commented on pyproject.toml
> +sentry-sdk = {extras = ["fastapi"], version = "^1.24.0"}
Так версия жеж указана 1.24.0

2023-05-29 18:55 UTC, wiky-avis commented on pyproject.toml
> +sentry-sdk = {extras = ["fastapi"], version = "^1.24.0"}
без ^

2023-05-29 19:03 UTC, opodryadov commented on pyproject.toml
> +sentry-sdk = {extras = ["fastapi"], version = "^1.24.0"}
пофиксил

2023-05-29 19:17 UTC, T1rax requested changes
По идее крайне желательно именно докер поправить, остальное на обсуждение

2023-05-29 19:17 UTC, T1rax commented on docker-compose-prod.yml
> +      - logstash
А почему убрал зависимость от Фаст апи? Он же нужен для работы, разве нет?

2023-05-29 19:17 UTC, T1rax commented on docker-compose-prod.yml
> +      - logstash
И зависимости можно ставить только на контейнеры, которые указаны в файле. Тут не вижу логстеш

2023-05-29 19:17 UTC, T1rax commented on docker-compose-prod.yml
> +      file: docker-compose-base.yml
В базовом фалйе нет нгинкса, его не получится экстенднуть, он тут и создается

2023-05-29 19:17 UTC, T1rax commented on docker-compose-prod.yml
> +      file: docker-compose-base.yml
По идее нужно оставить как раньше и по необходимости добавить в зависимости логстеш

2023-05-29 19:17 UTC, T1rax commented on nginx/conf.d/site.conf
> +    location / {
А почему переделал путь апишки?

2023-05-29 19:17 UTC, T1rax commented on src/app.py
> +    if settings.enable_sentry:
Не проще тогда init_sentry запускать через if?
А то так может показаться, что он всегда включается

2023-05-29 19:17 UTC, T1rax commented on src/app.py
> +    if settings.enable_sentry:
Как с трейсером ниже

2023-05-29 19:17 UTC, T1rax commented on src/app.py
> +@app.middleware("http")
Тут вот не понятно, как лучше поступить. Роутеры добавляются в create_app, а мидлварь добавляется вовне. Тут тогда либо мидлварь туда есть смысл добавить, либо роутеры тоже снаружи добавлять

Я бы с Викой тоже обсудил как лучше @wiky-avis

2023-05-29 19:24 UTC, opodryadov commented on docker-compose-prod.yml
> +      file: docker-compose-base.yml
Да, пропустил, поправлю

2023-05-29 19:25 UTC, opodryadov commented on docker-compose-prod.yml
> +      - logstash
При переносе в другой docker-compose.yml со старого не убрал.

2023-05-29 19:26 UTC, opodryadov commented on nginx/conf.d/site.conf
> +    location / {
а к чему здесь быть /event_api? можно, конечно, и обратно вернуть, но я полагаю, что когда мы будем все модули воедино объединять, то урлы все равно переделывать придется, так или иначе. вернуть на место event_api?

2023-05-29 19:27 UTC, opodryadov commented on src/app.py
> +@app.middleware("http")
можно и вынести отдельно middleware

2023-05-29 19:29 UTC, opodryadov commented on src/app.py
> +    if settings.enable_sentry:
да, пожалуй сделаю в едином формате)

2023-05-29 20:16 UTC, T1rax commented on nginx/conf.d/site.conf
> +    location / {
На данный момент у нас и асинк апи, и ugc живут на 80 порте. Тогда мешается логика. В целом желательно функциональность под свой путь прятать, домашняя страница вообще пустой может быть

Я сейчас сразу бы сделал свои пути, потому что тесты под них написаны и не придется их потом переписывать

2023-05-30 06:15 UTC, T1rax approved these changes

2023-05-30 06:51 UTC, merged